
"use client"

import { Bar, BarChart, CartesianGrid, XAxis, YAxis, ResponsiveContainer } from "recharts"
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { ChartConfig, ChartContainer, ChartTooltip, ChartTooltipContent } from "@/components/ui/chart"
import { Info } from "lucide-react";

// baseChartConfig is not effectively used for color if dataKey isn't 'desktop' or 'mobile'.
// const baseChartConfig = {
//   desktop: {
//     label: "Desktop", 
//     color: "hsl(var(--chart-1))",
//   },
//   mobile: { 
//     label: "Mobile",
//     color: "hsl(var(--chart-2))",
//   },
// } satisfies ChartConfig;

interface ChartDataItem {
  month: string;
  [key: string]: any; // Allow other keys like revenue, users, etc.
}

interface PerformanceChartProps {
  title: string;
  description: string;
  dataKey: string; 
  data: ChartDataItem[];
}

export function PerformanceChart({ title, description, dataKey, data }: PerformanceChartProps) {
  // Ensure dataKey is always part of the config for the label,
  // and explicitly set the color to silver (chart-3)
  const dynamicChartConfig = {
    [dataKey]: {
      label: title, // Use the chart title as the label for the data key
      color: `hsl(var(--chart-3))`, // Use chart-3 for silver
    }
  } as ChartConfig;

  return (
    <Card className="shadow-lg">
      <CardHeader>
        <CardTitle className="font-headline">{title}</CardTitle>
        <CardDescription>{description}</CardDescription>
      </CardHeader>
      <CardContent>
        {data && data.length > 0 ? (
          <ChartContainer config={dynamicChartConfig} className="h-[300px] w-full">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart accessibilityLayer data={data} margin={{ top: 5, right: 20, left: -20, bottom: 5 }}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="hsl(var(--border))" />
                <XAxis
                  dataKey="month"
                  tickLine={false}
                  tickMargin={10}
                  axisLine={false}
                  stroke="hsl(var(--muted-foreground))"
                  tickFormatter={(value) => value.slice(0, 3)}
                />
                <YAxis stroke="hsl(var(--muted-foreground))" tickLine={false} axisLine={false} tickMargin={10} />
                <ChartTooltip
                  cursor={false}
                  content={<ChartTooltipContent indicator="dashed" hideLabel />}
                />
                <Bar dataKey={dataKey} fill={`var(--color-${dataKey})`} radius={4} />
              </BarChart>
            </ResponsiveContainer>
          </ChartContainer>
        ) : (
          <div className="h-[300px] flex flex-col items-center justify-center text-muted-foreground">
            <Info className="h-10 w-10 mb-2" />
            <p>No data available to display.</p>
            <p className="text-xs">This chart will populate once data is generated by the simulation.</p>
          </div>
        )}
      </CardContent>
    </Card>
  )
}

